{4112}{4172}www.titulky.com
{4192}{4264}Paní Pitersonová.
{4265}{4336}Nazdar Rede.
{4384}{4475}Leí tam na stole.
{4766}{4814}Přítí zásilku budu|mít pro tebe ve čtvrtek.
{4815}{4899}Tak ve čtvrtek.
{7848}{7920}... čas je neúprosný,
{7944}{8015}a jsme zdraví nebo nemocní,
{8135}{8206}můe nás zničit nebo nám pomoci
{8254}{8326}... protoe ná ivot,|i nae smrt jsou závislé na čase,
{8327}{8393}který se nikdy nevrací.
{8421}{8493}A komukoli zakazuji ztrácet pojem o čase.
{8494}{8565}Právě je  13:56.
{8565}{8656}Co znamená, e máme 3h a 4min,|ne se začnou třídit zásilky.
{8732}{8804}Tolik máme času !
{8804}{8885}Ne se konkurence pokusí|o toté dřív ne my !
{8923}{8995}A, Mikolaj
{8995}{9087}Co je nového ?|Poprvé jsi doručil nai zásilku,
{9114}{9206}to si zaslouí něco zvlátního,|dostane za to Snikers a CD player.
{9282}{9343}A k tomu dobrou desku,|Elvis Presley,
{9344}{9393}50 miliónů fanouků|- to nemůe být omyl.
{9401}{9473}Poznáváte to, e ano.
{9474}{9559}Poslal jsem si to,|ne jsem odjel z Memphisu.
{9664}{9736}Co to můe být ?
{9903}{9974}To jsou .. , hodiny !
{9975}{10076}Kdy jsem je zapojil,byly vynulovány|a teď je 87 hodin a 22 minut.
{10118}{10210}Z Memphisu v Americe|k Mikolajovi v Rusku za 87 hodin.
{10237}{10319}87 je zahanbující prohra.
{10333}{10421}Jsou to jenom hodiny,|ale co kdyby to bylo něco jiného,
{10452}{10499}jako například:|tvůj ek nebo ádost o adopci!
{10500}{10571}87 hodin je celá věčnost !
{10572}{10669}Vesmír byl stvořen mnohem rychleji,|v průběhu 87 hodin zanikly národy.
{10691}{10783}A majetky byly získávány|za tuté dobu.
{10882}{10953}Co ?|Co jsi jim o mě vykládal.
{10954}{11026}Řekl jsem jim to, co chtěli slyet,|e aby jsi doručil zásilku,
{11027}{11089}ukradl jsi chlapci kolo.
{11097}{11199}Půjčil, ... půjčil jsem si kolo|od toho chlapce a doručil zásilku.
{11217}{11389}A právě tak máte konat,|protoe za 3 hodiny a 2 minuty od teď
{11336}{11428}kadý z těchto balíků musí být|na té dodávce a na cestě na letitě.
{11480}{11551}15 minut !
{11575}{11657}Pohyb,  każdá sekunda má cenu zlata.
{11719}{11790}Máme problém !
{11790}{11862}Jedno auto uvízlo.
{12220}{12292}No dobrá, Postavte tu stůl,|bude to třeba přenést.
{12316}{12388}Mnohokrát díky.
{12435}{12507}Honem, vytáhněte odtud vechno.
{12507}{12599}Dva směry, jeden k dodávce na letitě,|druhý k této dodávce.
{12722}{12809}Mikolaji, raz dva raz dva 4 minuty.
{12866}{12957}Ahoj, tady Kelly, pokud volá Chuckovi zavěs,|pokud ne, zanechej vzkaz.
{12985}{13067}Ahoj Kelly, pokud tam jsi,|zvedni to ... nejsi.
{13104}{13176}Nemohu tomu uvěřit,|třídím zásilky na Rudém náměstí.
{13248}{13319}Stýská se mi, chci tě líbat.
{13343}{13435}Odjídím odtud za 2 minuty,|jedu do Paříe a v Memphisu budu za 18 hodin.
{13463}{13535}Tak to byla dobrá zpráva,|patná je ta, e musím jít k zubaři.
{13582}{13654}Miluji tě, brzy se uvidíme,|a ví co to znamená.
{13654}{13726}Mikolaji ! Raz dva, raz dva.
{14156}{14227}Dnes večer musím být v Memphisu.
{14251}{14323}Já ti nepomůu,|pokecej z UPS.
{14419}{14490}Guen, je ná pilot v pořádku,|nejsou tady ádné léky.
{14514}{14538}Nestará se ?
{14538}{14586}Jsem vystraená,|ale holka musí dělat to co umí.
{14586}{14657}Obdivuji tvoji odvahu.
{14705}{14777}A co můe čekat od člověka,|který ukradl dítěti kolo.
{14777}{14849}Půjčil jsem si ho, ale ...
{14873}{14944}Tak tedy nechal jsi naloit|poslední dodávku, 2 minuty.
{14944}{15016}Prakticky to nebyly ani 2 minuty.
{15040}{15087}Letadlo není tak těké,|můe načerpat palivo , zrychlit a stihnout to.
{15088}{15159}Tady u nejde o dodávky.
{15159}{15231}Teď to byly 2 minuty,|přítě bude jetě víc,
{15303}{15374}a se nakonec změníme|na Americkou potu.
{15518}{15589}Hej, nedívej se tak na mě,|to je jen citrusová áva.
{15637}{15709}Ano, vypadá to jak|citrusová áva z roku 1992.
{15709}{15780}Nic sem neviděla.
{15780}{15862}Dali bychom Ti troku,|ale někdo se musí starat o letadlo.
{15876}{15924}Jasně, vak jsem ji ve řekla, ne ?
{15924}{16013}Hele Stane, chtěla jsem se zeptat,|... Jak se daří Marry?
{16139}{16211}Vlastně jetě nic nevíme
{16234}{16306}Předevčírem byla u doktora
{16330}{16402}Asi má rakovinu.
{16497}{16569}Časem se vechno vysvětlí.
{16569}{16641}Je mi to opravdu líto.
{16641}{16711}Vzka jí, prosím Tě,|e se za ní zastavím, a budu mít volno.
{16712}{16764}Chci, abys věděl,|e vichni na vás myslíme.
{16765}{16834}..slyel jsem o tom doktorovi z Atlanty,|prý je nejlepí.
{16835}{16894}Léčil manelku Franka Torada.
{17011}{17083}Ale k věci !
{17083}{17154}Můu na něj sehnat číslo.
{17226}{17298}Mohli byste se s ním setkat ...
{17322}{17393}... moná se podaří vemu předejít.
{17465}{17537}Díky Chacku.
{17537}{17608}Najdu jeho číslo.
{18110}{18158}Je tu někde Kelly ?
{18158}{18229}Je u kopírky.
{18946}{18994}Konečně jsi doma.
{18994}{19066}V podstatě.
{19066}{19137}Jsem velice ráda, e jsi doma.
{19926}{20008}... v Sarajevě strávil den s dětmi,|rozdával dárky ...
{20021}{20093}a zdobil vánoční stromeček.
{20929}{21001}A není ten krocan trochu suchý?
{21001}{21073}Nééé.
{22124}{22195}.. kdy u mluvíme o manelství,|kdy konečně poádá Kelly o ruku ?
{22196}{22267}Jak dlouho ? ?
{22267}{22338}40 minut ne se zmínil o manelství,|take jsem vyhrál.
{22339}{22411}Dluím Ti 5 dolarů.
{22435}{22506}...manelství...
{22506}{22593}Kelly se stále vrací k té ubohé známosti|s tím kloboučníkem.
{22602}{22673}Byl to právník.
{22745}{22837}Kelly pamatuje si,|jak si narazil lopatku ?
{22841}{22912}Narazil jsi ji,|kdy mi otvíral dveře.
{22912}{22984}Kelly byla jsi ji vdaná ?
{23414}{23485}óóó nael jsi olivu,|já si myslela, e jsem je vechny vyhodila.
{23486}{23558}Néé to néé.
{24203}{24227}OK krtám sobotu.
{24227}{24298}Ne...
{24298}{24380}Sobota je ji krtnuta,|ale na Silvestra tu musí být.
{24585}{24633}Dobrá, budu si muset|přehodit Jiní Ameriku.
{24633}{24704}V tom případě to budu muset|zařídit na 14-ho.
{24752}{24824}Hlavně abys byl na Silvestra.
{24824}{24896}Určitě doma .. přísahám.
{24919}{24967}Co ?
{24967}{25039}A co z naimi dárky,|mám pro tebe dárek.
{25134}{25206}Musíme to zařídit v autě.
{25517}{25588}Dejte mi dvě minuty,|jen dvě minuty ... díky.
{25636}{25708}Veselé vánoce.
{25708}{25780}Co je to?|Novodobá třpytka na ryby?
{25851}{25923}Tady má svůj noík.
{26305}{26353}Je skvělí.
{26353}{26425}Můj děda ho pouíval|nad Jiním Pacifikem.
{26496}{26568}To je moje oblíbená fotka.
{26616}{26707}Ví co udělám?|Vdycky budu na nich mít čas v Memphisu.
{26926}{26974}Nic jsi neřekla|o mých dárcích, nelíbí se Ti?
{26974}{27046}Ne, omlouvám se.
{27070}{27141}A co pager?
{27189}{27213}Líbí se Ti ten pager,|nebo ne?
{27213}{27261}Ano, velmi,
{27261}{27343}zvlátě, kdy je|v jedné z těch ruských panenek.
{27380}{27452}Není to ten hlasitý ?
{27452}{27524}Ne, můe ho naprogramovat,|má i vibrace, světlo ...
{27572}{27619}Vypadá opravdu jako| ... pager.
{27619}{27691}Omlouvám se za ručníky.
{27691}{27715}Ne, ne, jsou překrásné.
{27715}{27786}Vdy, kdy si budu mít ruce,|budu myslet na tebe.
{27787}{27858}Dobře, musím u jít,|astné a veselé.
{27906}{27978}Miluji Tě.|Já tebe taky.
{28145}{28217}Chacku !|Klíče!
{28456}{28537}Skoro jsem zapomněl,|mám pro tebe jetě jeden dárek!
{28623}{28694}Nemělo by se to ale otvírat v autě ..
{28742}{28814}... tak jak ručníky,|které byly z legrace.
{28957}{29029}Jsem překvapená.
{29053}{29135}Jestli to vydrí,|můe ho otevřít na Silvestra.
{29196}{29268}Miluji Tě.
{29316}{29387}Hned jsem zpátky !
{30415}{30463}Alle, kde to jsme ?
{30463}{30534}Někde nad Pacifikem.
{30701}{30773}A ty turbulence,|to je normální?
{31108}{31179}... FedEx pozice 1.5.2.6...
{31227}{31299}... jsme 200 mil na jih ...
{31442}{31514}... FedEx 88, jak mě slyíte ?
{31538}{31609}Zkoueli jste vyí frekvenci ?
{31801}{31872}... FedEx 88 slyíte mě ?
{33521}{33592}Chytej to !!
{35671}{35743}Chacku ! Nehni se odtud !
{52205}{52277}Slyí mě někdo ?!
{52539}{52611}Kdokoliv !!!
{52683}{52754}pomoc !
{52778}{52850}POMOC !
{55837}{55908}Co to je ?!
{56386}{56458}Je tam někdo ?
{69575}{69647}Allen Albert.
{71582}{71654}Take tolik.
{75859}{75930}Loď !
{76002}{76050}Loď !
{76050}{76122}Tady !
{76361}{76432}Tady !
{76480}{76552}Pomozte mi,|tady !
{76576}{76647}Koukněte!
{76647}{76719}S   O   S
{76743}{76814}Tak dál !
{90027}{90099}Pěkné narozeniny.
{90123}{90194}Nejkrásnějí věc na světě je sám svět.
{90266}{90358}Johny nech tyto tvé narozeniny|jsou nejlepí ze vech ... dědeček.
{94830}{94901}Tak dál.
{102117}{102189}Vzduch to zařídí !
